config/routes.rb
AccountManager::Application.routes.draw do
  root to: 'home#index'

  get '/', to: 'home#index', as: 'home'
  get '/register', to: 'holders#new', as: 'register'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :holders, only: [:create, :show, :edit, :update]
  resources :accounts, except: [:destroy] do
    resources :transactions, only: [:new, :create, :edit, :update]
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  KINDS = ['Checking', 'Savings']

  has_many :transactions
  has_many :holder_accounts
  has_many :holders, through: :holder_accounts

  validates :name, presence: :true
  validates :kind, inclusion: { in: KINDS.map(&:downcase) }
end

app/models/holder.rb
class Holder < ActiveRecord::Base
  has_secure_password

  has_many :transactions
  has_many :holder_accounts
  has_many :accounts, through: :holder_accounts

  validates :password, confirmation: true
end

app/models/holder_account.rb
class HolderAccount < ActiveRecord::Base
  belongs_to :holder
  belongs_to :account
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  KINDS = ['Deposit', 'Withdraw']
  belongs_to :holder
  belongs_to :account

  validates :kind, inclusion: { in: KINDS.map(&:downcase) }
  validates :amount, numericality: { greater_than_or_equal_to: 0.01 }
  validates :description, presence: true

  def amount
    read_attribute(:amount).to_f / 100
  end

  def amount=(dollars)
    write_attribute(:amount, (dollars.to_f * 100).to_i)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update]

  def index
    @accounts = current_holder.accounts
  end

  def show
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    @account.holders << current_holder

    if @account.save
      flash[:notice] = "Your account was created."
      redirect_to accounts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @account.update(account_params)
      flash[:notice] = "Your account was successfully updated."
      redirect_to account_path(@account)
    else
      render :edit
    end
  end

  private

  def account_params
    params.require(:account).permit(:name, :kind)
  end

  def set_account
    @account = Account.find params[:id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_holder, :logged_in?

  def current_holder
    @current_holder ||= Holder.find(session[:holder_id]) if session[:holder_id]
  end

  def logged_in?
    !!current_holder
  end
end

app/controllers/holders_controller.rb
class HoldersController < ApplicationController
  def new
    @holder = Holder.new
  end

  def create
    @holder = Holder.new(holder_params)

    if @holder.save
      session[:holder_id] = @holder.id
      flash[:notice] = "Your profile was created."
      redirect_to holder_path(@holder)
    else
      render :new
    end
  end

  def show
    @holder = Holder.find params[:id]
  end

  private

  def holder_params
    params.require(:holder).permit(:name, :password, :password_confirmation)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    holder = Holder.find_by(name: params[:name])

    if holder && holder.authenticate(params[:password])
      # login
      session[:holder_id] = holder.id
      flash[:notice] = "Welcome, you've logged in."
      redirect_to accounts_path
    else
      # error on login form
      flash[:error] = "There's something wrong with your username or password."
      redirect_to login_path
    end
  end

  def destroy
    session[:holder_id] = nil
    flash[:notice] = "You have been logged out."
    redirect_to root_path
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_account, only: [:new, :create, :edit, :update]
  before_action :set_transaction, only: [:edit, :update]

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.account = @account

    if @transaction.save
      flash[:notice] = "Your transaction was created."
      redirect_to account_path(@account)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @transaction.update(transaction_params)
      flash[:notice] = "Your transaction was successfully updated."
      redirect_to account_path(@account)
    else
      render :edit
    end
  end

  private

  def transaction_params
    strong_params = params.require(:transaction).permit(:kind, :amount, :description)
  end

  def set_transaction
    @transaction = Transaction.find params[:id]
  end

  def set_account
    @account = Account.find params[:account_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_amount(dollars)
    format("%.2f", dollars)
  end
end

app/views/accounts/_form.html.erb
<%= form_for account do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :kind, 'Type' %>
    <%= f.select(:kind, Account::KINDS.map { |k| [k, k.downcase] }, {}, { class: 'form-control' }) %>
  </div>
  <%= f.submit((account.new_record? ? 'Create' : 'Update') + ' Account' , class: 'btn btn-success') %>
<% end %>

app/views/accounts/edit.html.erb
<%= render 'shared/content_title', title: "Edit Account: #{@account.name}" %>

<div class="btn-group">
  <%= link_to "Back to Account", account_path(@account), class: "btn btn-warning" %>
</div>

<%= render 'shared/errors', obj: @account %>

<%= render 'form', account: @account %>

app/views/accounts/index.html.erb
<%= render 'shared/content_title', title: 'Accounts' %>

<div class="btn-group">
  <%= link_to "Create New Account", new_account_path, class: "btn btn-success" %>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Balance</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @accounts.each do |acc| %>
      <tr>
        <td><%= acc.name %></td>
        <td><%= acc.kind %></td>
        <td><%= acc.balance %></td>
        <td>
          <div class="btn-group">
            <%= link_to 'View', account_path(acc), class: "btn btn-success" %>
            <%= link_to 'Edit', edit_account_path(acc), class: "btn btn-primary" %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/accounts/new.html.erb
<%= render 'shared/content_title', title: 'Create New Account' %>

<div class="btn-group">
  <%= link_to "Back to All Accounts", accounts_path, class: "btn btn-warning" %>
</div>

<%= render 'shared/errors', obj: @account %>

<%= render 'form', account: @account %>

app/views/accounts/show.html.erb
<%= render 'shared/content_title', title: @account.name, subtitle: @account.kind.capitalize %>

<div class="btn-group" role="group">
  <%= link_to 'New Transaction', new_account_transaction_path(@account), class: 'btn btn-success' %>
  <%= link_to 'Edit Account', edit_account_path(@account), class: 'btn btn-primary' %>
  <%= link_to 'Back to All Accounts', accounts_path, class: 'btn btn-warning' %>
</div>

<h3>Transactions</h3>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Type</th>
      <th>Description</th>
      <th>Amount</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @account.transactions.each do |trans| %>
      <tr>
        <td><%= trans.kind %></td>
        <td><%= trans.kind %></td>
        <td><%= trans.amount %></td>
        <td>
          <%= link_to 'Edit', edit_account_transaction_path(@account, trans), class: "btn btn-primary" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/holders/_form.html.erb
<%= form_for @holder do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, 'Confirm Password' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <%= f.submit "Register", class: 'btn btn-success' %>
<% end %>

app/views/holders/new.html.erb
<%= render 'shared/content_title', title: 'Register' %>

<%= render 'shared/errors', obj: @holder %>

<%= render 'form' %>

app/views/holders/show.html.erb
<%= render 'shared/content_title', title: @holder.name %>

app/views/home/index.html.erb
<h2>Welcome to Account Manager!</h2>
<p>Please register/login to view and create accounts.</p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <%= link_to "Account Manager", root_path, class: 'navbar-brand' %>
    <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li>
          <%= link_to "Logout", logout_path, class: 'btn' %>
        </li>
      <% else %>
        <li>
          <%= link_to "Register", register_path, class: 'btn' %>
        </li>
        <li>
          <%= link_to "Login", login_path, class: 'btn' %>
        </li>
      <% end %>
    </ul>
    <% if logged_in? %>
      <p class="navbar-text navbar-right"><small>Logged in as <%= current_holder.name %>.</small></p>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AccountManager</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render 'layouts/navigation' %>
  </header>
  <main class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </main>
</body>
</html>

app/views/shared/_content_title.html.erb
<% subtitle ||= false %>

<div class='page-header'>
  <h1>
    <%= title %>
    <% if subtitle %>
      <small><%= subtitle %></small>
    <% end %>
  </h1>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/transactions/_form.html.erb
<%= form_for [account, transaction] do |f| %>
  <div class="form-group">
    <%= f.label :kind, 'Type' %>
    <%= f.select(:kind, Transaction::KINDS.map { |k| [k, k.downcase] }, {}, { class: 'form-control' }) %>
  </div>
  <div class="form-group">
    <%= f.label :amount %>
    <%= f.text_field :amount, value: display_amount(transaction.amount), class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <%= f.submit((transaction.new_record? ? 'Create' : 'Update') + ' Transaction', class: 'btn btn-success') %>
<% end %>

app/views/transactions/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Transaction' %>

<div class="btn-group">
  <%= link_to "Back to Account", account_path(@account), class: "btn btn-warning" %>
</div>

<%= render 'shared/errors', obj: @transaction %>

<%= render 'form', account: @account, transaction: @transaction %>

app/views/transactions/new.html.erb
<%= render 'shared/content_title', title: 'Create New Transaction' %>


<div class="btn-group">
  <%= link_to "Back to Account", account_path(@account), class: "btn btn-warning" %>
</div>

<%= render 'shared/errors', obj: @transaction %>

<%= render 'form', account: @account, transaction: @transaction %>